# frozen_string_literal: true

puts 'Start inserting Insects data'

# https://konchu-zukan.info/japanese_syllabary.php
insects = [
  { name: 'アオスジアゲハ', sex: 'オス',size:"55～65mm", lifespan:"2週間〜1ヶ月", biological_family_id: 2,habitat_place_id: 3},
  { name: 'アオタテハモドキ', sex: 'オス', size:"55～60mm", lifespan:"2週間〜3ヶ月",biological_family_id: 30,habitat_place_id:1 },
  { name: 'アオハダトンボ', sex: 'オス',size:"55mm", lifespan:"2ヶ月", biological_family_id: 15,habitat_place_id:2 },
  { name: 'アオマツムシ', sex: 'オス', size:"24mm", lifespan:"3ヶ月",biological_family_id: 20,habitat_place_id: 1},
  { name: 'アカシジミ', sex: 'オス', size:"35～45mm", lifespan:"1ヶ月",biological_family_id: 23,habitat_place_id:1 },
  { name: 'アカタテハ', sex: 'オス', size:"50~60mm", lifespan:"4〜6ヶ月",biological_family_id: 30,habitat_place_id: 1},
  { name: 'アカハナカミキリ', sex: 'オス',size:"12~22mm", lifespan:"2〜4ヶ月",biological_family_id: 13,habitat_place_id:3 },
  { name: 'アキアカネ', sex: 'オス', size:"40mm", lifespan:"3〜4ヶ月",biological_family_id: 35,habitat_place_id: 2},
  { name: 'アサギマダラ', sex: 'オス', size:"100mm", lifespan:"4〜5ヶ月",biological_family_id: 42,habitat_place_id:1 },
  { name: 'アブラゼミ', sex: 'オス', size:"50～60mm", lifespan:"2〜3週間",biological_family_id: 29,habitat_place_id:3 },
  { name: 'アメンボ', sex: 'オス',size:"11～16mm", lifespan:"1〜3ヶ月", biological_family_id: 3,habitat_place_id: 2},
  { name: 'イシガケチョウ', sex: 'オス',size:"45～55mm", lifespan:"2〜3ヶ月",biological_family_id: 30,habitat_place_id:1 },
  { name: 'イチモンジセセリ', sex: 'オス',size:"34～45mm", lifespan:"1〜2ヶ月", biological_family_id: 28,habitat_place_id:1 },
  { name: 'エンマコオロギ', sex: 'オス',size:"23～32mm", lifespan:"1〜2ヶ月", biological_family_id: 20,habitat_place_id: 1},
  { name: 'オオウラギンスジヒョウモン', sex: 'オス',size:"60～75mm", lifespan:"2〜3ヶ月", biological_family_id: 30 ,habitat_place_id:1},
  { name: 'オオクワガタ', sex: 'オス',size:"30～78mm", lifespan:"2〜3年", biological_family_id: 19,habitat_place_id:3 },
  { name: 'オオゴマダラ', sex: 'オス', size:"120mm", lifespan:"4〜5ヶ月",biological_family_id: 42 ,habitat_place_id:3},
  { name: 'オオスズメバチ', sex: 'オス',size:"30～45mm", lifespan:"1ヶ月〜1年", biological_family_id: 27 ,habitat_place_id:3},
  { name: 'オオゾウムシ', sex: 'オス', size:"12～24mm", lifespan:"1年",biological_family_id: 8 ,habitat_place_id:3},
  { name: 'オオムラサキ', sex: 'オス',size:"75～100mm", lifespan:"1ヶ月", biological_family_id: 30 ,habitat_place_id:3},
  { name: 'オトシブミ', sex: 'オス',size:"7～10mm", lifespan:"1.5ヶ月", biological_family_id: 10 ,habitat_place_id:3},
  { name: 'オニヤンマ', sex: 'オス',size:"95～100mm", lifespan:"1〜2ヶ月", biological_family_id: 11 ,habitat_place_id:2},
  { name: 'オンブバッタ', sex: 'オス',size:"25～45mm", lifespan:"3ヶ月", biological_family_id: 12 ,habitat_place_id:1},
  { name: 'カナブン', sex: 'オス', size:"23～29mm", lifespan:"1〜2ヶ月",biological_family_id: 21 ,habitat_place_id:3},
  { name: 'カブトムシ', sex: 'オス',size:"30～53mm", lifespan:"1〜3ヶ月", biological_family_id: 21 ,habitat_place_id:3},
  { name: 'カラスアゲハ', sex: 'オス',size:"80～120mm", lifespan:"1〜2週間", biological_family_id: 2 ,habitat_place_id:3},
  { name: 'カンタン', sex: 'オス',size:"12mm", lifespan:"2〜3ヶ月", biological_family_id: 20 ,habitat_place_id:1},
  { name: 'キリギリス', sex: 'オス',size:"35mm", lifespan:"2〜3ヶ月", biological_family_id: 17 ,habitat_place_id:1},
  { name: 'ギンヤンマ', sex: 'オス',size:"70mm", lifespan:"2〜3ヶ月", biological_family_id: 46,habitat_place_id:2 },
  { name: 'クマゼミ', sex: 'オス',size:"60～70mm", lifespan:"2〜3週間", biological_family_id: 29,habitat_place_id: 3},
  { name: 'クマバチ', sex: 'オス', size:"23mm", lifespan:"1年",biological_family_id: 22 ,habitat_place_id:3},
  { name: 'クロアゲハ', sex: 'オス',size:"80～120mm", lifespan:"2〜3週間", biological_family_id: 2 ,habitat_place_id:2},
  { name: 'ゲンジボタル', sex: 'オス',size:"12～18mm", lifespan:"1〜2週間", biological_family_id: 41 ,habitat_place_id:2},
  { name: 'コクワガタ', sex: 'オス', size:"16~45mm", lifespan:"1〜2年",biological_family_id: 19 ,habitat_place_id:3},
  { name: 'ゴマダラカミキリ', sex: 'オス',size:"25～35mm", lifespan:"3〜4ヶ月", biological_family_id: 13 ,habitat_place_id:3},
  { name: 'シオカラトンボ', sex: 'オス',size:"50~55mm", lifespan:"1〜2ヶ月", biological_family_id: 35 ,habitat_place_id:2},
  { name: 'ショウリョウバッタ', sex: 'オス',size:"45~90mm", lifespan:"4〜5ヶ月", biological_family_id: 37 ,habitat_place_id:1},
  { name: 'トノサマバッタ', sex: 'オス',size:"45~50mm", lifespan:"3〜4ヶ月", biological_family_id: 37,habitat_place_id: 1},
  { name: 'ナミテントウ', sex: 'オス', size:"8mm", lifespan:"2〜3ヶ月",biological_family_id: 34 ,habitat_place_id:1},
  { name: 'ノコギリクワガタ', sex: 'オス', size:"24～71mm", lifespan:"3〜4ヶ月",biological_family_id: 19 ,habitat_place_id:3},
  { name: 'ハンミョウ', sex: 'オス', size:"20mm", lifespan:"3〜4ヶ月",biological_family_id: 39 ,habitat_place_id:4},
  { name: 'マイマイカブリ', sex: 'オス',size:"40～65mm", lifespan:"2〜4年", biological_family_id: 9 ,habitat_place_id:3},
  { name: 'ミヤマクワガタ', sex: 'オス', size:"25~79mm", lifespan:"3ヶ月",biological_family_id: 19 ,habitat_place_id:3},
  { name: 'ミンミンゼミ', sex: 'オス', size:"60mm", lifespan:"2～3週間",biological_family_id: 29 ,habitat_place_id:3},
  { name: 'ヤマトシジミ', sex: 'オス',size:"20～29mm", lifespan:"1ヶ月", biological_family_id: 23 ,habitat_place_id:1},
  { name: 'リュウキュウアサギマダラ', sex: 'オス',size:"70~85mm", lifespan:"1～3ヶ月", biological_family_id: 30 ,habitat_place_id:1},
  { name: 'ルリタテハ', sex: 'オス', size:"50～65mm", lifespan:"6ヶ月",biological_family_id: 30 ,habitat_place_id:1},
  { name: 'アオスジアゲハ', sex: 'メス',size:"55～65mm", lifespan:"2週間〜1ヶ月", biological_family_id: 2,habitat_place_id: 3},
  { name: 'アオタテハモドキ', sex: 'メス', size:"55～60mm", lifespan:"2週間〜3ヶ月",biological_family_id: 30,habitat_place_id:1 },
  { name: 'アオハダトンボ', sex: 'メス',size:"55mm", lifespan:"2ヶ月", biological_family_id: 15,habitat_place_id:2 },
  { name: 'アオマツムシ', sex: 'メス', size:"24mm", lifespan:"3ヶ月",biological_family_id: 20,habitat_place_id: 1},
  { name: 'アカシジミ', sex: 'メス', size:"35～45mm", lifespan:"1ヶ月",biological_family_id: 23,habitat_place_id:1 },
  { name: 'アカタテハ', sex: 'メス', size:"50~60mm", lifespan:"4〜6ヶ月",biological_family_id: 30,habitat_place_id: 1},
  { name: 'アカハナカミキリ', sex: 'メス',size:"12~22mm", lifespan:"2〜4ヶ月",biological_family_id: 13,habitat_place_id:3 },
  { name: 'アキアカネ', sex: 'メス', size:"40mm", lifespan:"3〜4ヶ月",biological_family_id: 35,habitat_place_id: 2},
  { name: 'アサギマダラ', sex: 'メス', size:"100mm", lifespan:"4〜5ヶ月",biological_family_id: 42,habitat_place_id:1 },
  { name: 'アブラゼミ', sex: 'メス', size:"50～60mm", lifespan:"2〜3週間",biological_family_id: 29,habitat_place_id:3 },
  { name: 'アメンボ', sex: 'メス',size:"11～16mm", lifespan:"1〜3ヶ月", biological_family_id: 3,habitat_place_id: 2},
  { name: 'イシガケチョウ', sex: 'メス',size:"45～55mm", lifespan:"2〜3ヶ月",biological_family_id: 30,habitat_place_id:1 },
  { name: 'イチモンジセセリ', sex: 'メス',size:"34～45mm", lifespan:"1〜2ヶ月", biological_family_id: 28,habitat_place_id:1 },
  { name: 'エンマコオロギ', sex: 'メス',size:"23～32mm", lifespan:"1〜2ヶ月", biological_family_id: 20,habitat_place_id: 1},
  { name: 'オオウラギンスジヒョウモン', sex: 'メス',size:"60～75mm", lifespan:"2〜3ヶ月", biological_family_id: 30 ,habitat_place_id:1},
  { name: 'オオクワガタ', sex: 'メス',size:"30～78mm", lifespan:"2〜3年", biological_family_id: 19,habitat_place_id:3 },
  { name: 'オオゴマダラ', sex: 'メス', size:"120mm", lifespan:"4〜5ヶ月",biological_family_id: 42 ,habitat_place_id:3},
  { name: 'オオスズメバチ', sex: 'メス',size:"30～45mm", lifespan:"1ヶ月〜1年", biological_family_id: 27 ,habitat_place_id:3},
  { name: 'オオゾウムシ', sex: 'メス', size:"12～24mm", lifespan:"1年",biological_family_id: 8 ,habitat_place_id:3},
  { name: 'オオムラサキ', sex: 'メス',size:"75～100mm", lifespan:"1ヶ月", biological_family_id: 30 ,habitat_place_id:3},
  { name: 'オトシブミ', sex: 'メス',size:"7～10mm", lifespan:"1.5ヶ月", biological_family_id: 10 ,habitat_place_id:3},
  { name: 'オニヤンマ', sex: 'メス',size:"95～100mm", lifespan:"1〜2ヶ月", biological_family_id: 11 ,habitat_place_id:2},
  { name: 'オンブバッタ', sex: 'メス',size:"25～45mm", lifespan:"3ヶ月", biological_family_id: 12 ,habitat_place_id:1},
  { name: 'カナブン', sex: 'メス', size:"23～29mm", lifespan:"1〜2ヶ月",biological_family_id: 21 ,habitat_place_id:3},
  { name: 'カブトムシ', sex: 'メス',size:"30～53mm", lifespan:"1〜3ヶ月", biological_family_id: 21 ,habitat_place_id:3},
  { name: 'カラスアゲハ', sex: 'メス',size:"80～120mm", lifespan:"1〜2週間", biological_family_id: 2 ,habitat_place_id:3},
  { name: 'カンタン', sex: 'メス',size:"12mm", lifespan:"2〜3ヶ月", biological_family_id: 20 ,habitat_place_id:1},
  { name: 'キリギリス', sex: 'メス',size:"35mm", lifespan:"2〜3ヶ月", biological_family_id: 17 ,habitat_place_id:1},
  { name: 'ギンヤンマ', sex: 'メス',size:"70mm", lifespan:"2〜3ヶ月", biological_family_id: 46,habitat_place_id:2 },
  { name: 'クマゼミ', sex: 'メス',size:"60～70mm", lifespan:"2〜3週間", biological_family_id: 29,habitat_place_id: 3},
  { name: 'クマバチ', sex: 'メス', size:"23mm", lifespan:"1年",biological_family_id: 22 ,habitat_place_id:3},
  { name: 'クロアゲハ', sex: 'メス',size:"80～120mm", lifespan:"2〜3週間", biological_family_id: 2 ,habitat_place_id:2},
  { name: 'ゲンジボタル', sex: 'メス',size:"12～18mm", lifespan:"1〜2週間", biological_family_id: 41 ,habitat_place_id:2},
  { name: 'コクワガタ', sex: 'メス', size:"16~45mm", lifespan:"1〜2年",biological_family_id: 19 ,habitat_place_id:3},
  { name: 'ゴマダラカミキリ', sex: 'メス',size:"25～35mm", lifespan:"3〜4ヶ月", biological_family_id: 13 ,habitat_place_id:3},
  { name: 'シオカラトンボ', sex: 'メス',size:"50~55mm", lifespan:"1〜2ヶ月", biological_family_id: 35 ,habitat_place_id:2},
  { name: 'ショウリョウバッタ', sex: 'メス',size:"45~90mm", lifespan:"4〜5ヶ月", biological_family_id: 37 ,habitat_place_id:1},
  { name: 'トノサマバッタ', sex: 'メス',size:"45~50mm", lifespan:"3〜4ヶ月", biological_family_id: 37,habitat_place_id: 1},
  { name: 'ナミテントウ', sex: 'メス', size:"8mm", lifespan:"2〜3ヶ月",biological_family_id: 34 ,habitat_place_id:1},
  { name: 'ノコギリクワガタ', sex: 'メス', size:"24～71mm", lifespan:"3〜4ヶ月",biological_family_id: 19 ,habitat_place_id:3},
  { name: 'ハンミョウ', sex: 'メス', size:"20mm", lifespan:"3〜4ヶ月",biological_family_id: 39 ,habitat_place_id:4},
  { name: 'マイマイカブリ', sex: 'メス',size:"40～65mm", lifespan:"2〜4年", biological_family_id: 9 ,habitat_place_id:3},
  { name: 'ミヤマクワガタ', sex: 'メス', size:"25~79mm", lifespan:"3ヶ月",biological_family_id: 19 ,habitat_place_id:3},
  { name: 'ミンミンゼミ', sex: 'メス', size:"60mm", lifespan:"2～3週間",biological_family_id: 29 ,habitat_place_id:3},
  { name: 'ヤマトシジミ', sex: 'メス',size:"20～29mm", lifespan:"1ヶ月", biological_family_id: 23 ,habitat_place_id:1},
  { name: 'リュウキュウアサギマダラ', sex: 'メス',size:"70~85mm", lifespan:"1～3ヶ月", biological_family_id: 30 ,habitat_place_id:1},
  { name: 'ルリタテハ', sex: 'メス', size:"50～65mm", lifespan:"6ヶ月",biological_family_id: 30 ,habitat_place_id:1},

]
sorted_data = insects.sort_by { |insect| [insect[:name], insect[:sex]] }
sorted_data.each do |data|
  Insect.create!(data)
end

puts 'Insects data created!'
