# frozen_string_literal: true

puts 'Start inserting Insects data'

# https://konchu-zukan.info/japanese_syllabary.php
insects = [
  { name: 'アオスジアゲハ', sex: 'オス', biological_family_id: 2 },
  { name: 'アオタテハモドキ', sex: 'オス', biological_family_id: 30 },
  { name: 'アオハダトンボ', sex: 'オス', biological_family_id: 15 },
  { name: 'アオマツムシ', sex: 'オス', biological_family_id: 20 },
  { name: 'アカシジミ', sex: 'オス', biological_family_id: 23 },
  { name: 'アカタテハ', sex: 'オス', biological_family_id: 30 },
  { name: 'アカハナカミキリ', sex: 'オス', biological_family_id: 13 },
  { name: 'アキアカネ', sex: 'オス', biological_family_id: 35 },
  { name: 'アサギマダラ', sex: 'オス', biological_family_id: 42 },
  { name: 'アブラゼミ', sex: 'オス', biological_family_id: 29 },
  { name: 'アメンボ', sex: 'オス', biological_family_id: 3 },
  { name: 'イシガケチョウ', sex: 'オス', biological_family_id: 30 },
  { name: 'イチモンジセセリ', sex: 'オス', biological_family_id: 28 },
  { name: 'エンマコオロギ', sex: 'オス', biological_family_id: 20 },
  { name: 'オオウラギンスジヒョウモン', sex: 'オス', biological_family_id: 30 },
  { name: 'オオクワガタ', sex: 'オス', biological_family_id: 19 },
  { name: 'オオゴマダラ', sex: 'オス', biological_family_id: 42 },
  { name: 'オオスズメバチ', sex: 'オス', biological_family_id: 27 },
  { name: 'オオゾウムシ', sex: 'オス', biological_family_id: 8 },
  { name: 'オオムラサキ', sex: 'オス', biological_family_id: 30 },
  { name: 'オトシブミ', sex: 'オス', biological_family_id: 10 },
  { name: 'オニヤンマ', sex: 'オス', biological_family_id: 11 },
  { name: 'オンブバッタ', sex: 'オス', biological_family_id: 12 },
  { name: 'カナブン', sex: 'オス', biological_family_id: 21 },
  { name: 'カブトムシ', sex: 'オス', biological_family_id: 21 },
  { name: 'カラスアゲハ', sex: 'オス', biological_family_id: 2 },
  { name: 'カンタン', sex: 'オス', biological_family_id: 20 },
  { name: 'キリギリス', sex: 'オス', biological_family_id: 17 },
  { name: 'ギンヤンマ', sex: 'オス', biological_family_id: 46 },
  { name: 'クマゼミ', sex: 'オス', biological_family_id: 29 },
  { name: 'クマバチ', sex: 'オス', biological_family_id: 22 },
  { name: 'クロアゲハ', sex: 'オス', biological_family_id: 2 },
  { name: 'ゲンジボタル', sex: 'オス', biological_family_id: 41 },
  { name: 'コクワガタ', sex: 'オス', biological_family_id: 19 },
  { name: 'ゴマダラカミキリ', sex: 'オス', biological_family_id: 13 },
  { name: 'シオカラトンボ', sex: 'オス', biological_family_id: 35 },
  { name: 'ショウリョウバッタ', sex: 'オス', biological_family_id: 37 },
  { name: 'トノサマバッタ', sex: 'オス', biological_family_id: 37 },
  { name: 'ナミテントウ', sex: 'オス', biological_family_id: 34 },
  { name: 'ノコギリクワガタ', sex: 'オス', biological_family_id: 19 },
  { name: 'ハンミョウ', sex: 'オス', biological_family_id: 39 },
  { name: 'マイマイカブリ', sex: 'オス', biological_family_id: 9 },
  { name: 'ミヤマクワガタ', sex: 'オス', biological_family_id: 19 },
  { name: 'ミンミンゼミ', sex: 'オス', biological_family_id: 29 },
  { name: 'ヤマトシジミ', sex: 'オス', biological_family_id: 23 },
  { name: 'リュウキュウアサギマダラ', sex: 'オス', biological_family_id: 30 },
  { name: 'ルリタテハ', sex: 'オス', biological_family_id: 30 },
  { name: 'アオスジアゲハ', sex: 'メス', biological_family_id: 2 },
  { name: 'アオタテハモドキ', sex: 'メス', biological_family_id: 30 },
  { name: 'アオハダトンボ', sex: 'メス', biological_family_id: 15 },
  { name: 'アオマツムシ', sex: 'メス', biological_family_id: 20 },
  { name: 'アカシジミ', sex: 'メス', biological_family_id: 23 },
  { name: 'アカタテハ', sex: 'メス', biological_family_id: 30 },
  { name: 'アカハナカミキリ', sex: 'メス', biological_family_id: 13 },
  { name: 'アキアカネ', sex: 'メス', biological_family_id: 35 },
  { name: 'アサギマダラ', sex: 'メス', biological_family_id: 42 },
  { name: 'アブラゼミ', sex: 'メス', biological_family_id: 29 },
  { name: 'アメンボ', sex: 'メス', biological_family_id: 3 },
  { name: 'イシガケチョウ', sex: 'メス', biological_family_id: 30 },
  { name: 'イチモンジセセリ', sex: 'メス', biological_family_id: 28 },
  { name: 'エンマコオロギ', sex: 'メス', biological_family_id: 20 },
  { name: 'オオウラギンスジヒョウモン', sex: 'メス', biological_family_id: 30 },
  { name: 'オオクワガタ', sex: 'メス', biological_family_id: 19 },
  { name: 'オオゴマダラ', sex: 'メス', biological_family_id: 42 },
  { name: 'オオスズメバチ', sex: 'メス', biological_family_id: 27 },
  { name: 'オオゾウムシ', sex: 'メス', biological_family_id: 8 },
  { name: 'オオムラサキ', sex: 'メス', biological_family_id: 30 },
  { name: 'オトシブミ', sex: 'メス', biological_family_id: 10 },
  { name: 'オニヤンマ', sex: 'メス', biological_family_id: 11 },
  { name: 'オンブバッタ', sex: 'メス', biological_family_id: 12 },
  { name: 'カナブン', sex: 'メス', biological_family_id: 21 },
  { name: 'カブトムシ', sex: 'メス', biological_family_id: 21 },
  { name: 'カラスアゲハ', sex: 'メス', biological_family_id: 2 },
  { name: 'カンタン', sex: 'メス', biological_family_id: 20 },
  { name: 'キリギリス', sex: 'メス', biological_family_id: 17 },
  { name: 'ギンヤンマ', sex: 'メス', biological_family_id: 46 },
  { name: 'クマゼミ', sex: 'メス', biological_family_id: 29 },
  { name: 'クマバチ', sex: 'メス', biological_family_id: 22 },
  { name: 'クロアゲハ', sex: 'メス', biological_family_id: 2 },
  { name: 'ゲンジボタル', sex: 'メス', biological_family_id: 41 },
  { name: 'コクワガタ', sex: 'メス', biological_family_id: 19 },
  { name: 'ゴマダラカミキリ', sex: 'メス', biological_family_id: 13 },
  { name: 'シオカラトンボ', sex: 'メス', biological_family_id: 35 },
  { name: 'ショウリョウバッタ', sex: 'メス', biological_family_id: 37 },
  { name: 'トノサマバッタ', sex: 'メス', biological_family_id: 37 },
  { name: 'ナミテントウ', sex: 'メス', biological_family_id: 34 },
  { name: 'ノコギリクワガタ', sex: 'メス', biological_family_id: 19 },
  { name: 'ハンミョウ', sex: 'メス', biological_family_id: 39 },
  { name: 'マイマイカブリ', sex: 'メス', biological_family_id: 9 },
  { name: 'ミヤマクワガタ', sex: 'メス', biological_family_id: 19 },
  { name: 'ミンミンゼミ', sex: 'メス', biological_family_id: 29 },
  { name: 'ヤマトシジミ', sex: 'メス', biological_family_id: 23 },
  { name: 'リュウキュウアサギマダラ', sex: 'メス', biological_family_id: 30 },
  { name: 'ルリタテハ', sex: 'メス', biological_family_id: 30 }
]

sorted_data = insects.sort_by { |insect| [insect[:name], insect[:sex]] }
sorted_data.each do |data|
  Insect.create!(data)
end

puts 'Insects data created!'
